### ISSUE TITLE
Package not working on python 3.11 on github CI (ModuleNotFoundError: No module named '_cffi_backend')

### ISSUE THREAD

**Issue by iTrooz** [memory/python-dpkg#12]
The package fails with the error `ModuleNotFoundError: No module named '_cffi_backend'` on a Github CI running Ubuntu 22.04 with python 3.11 : https://github.com/iTrooz/Test/actions/runs/3906424282/jobs/6674586163
Workflow file : https://github.com/iTrooz/Test/actions/runs/3906424282/workflow

The same workflow with python3.10 works fine : https://github.com/iTrooz/Test/actions/runs/3906438202/jobs/6674614888

I also tried a docker container with the same config, Ubuntu 22.04 and python 3.11, and it pydpkg is also imported without problem

(by "works fine" I mean "imports fine". I did not try anything besides that)

**Comment by memory** [comment]
Thanks for the heads up; I'll try to get this sorted out this weekend.

**Comment by n-oden** [comment]
https://github.com/memory/python-dpkg/pull/13

Interestingly, the test harness passes on 3.11, so I don't think this is a bug in pydpkg as such.  I suspect that this is an issue with whatever docker image github actions is providing under the `ubuntu-latest` alias, and with whatever python distribution is being installed by `apt`.

(deleting my first set of suggestions since on reflection they're kinda unhelpful-- longer comment to follow)

**Comment by n-oden** [comment]
Okay, actually my first set of suggestions were not too far off the mark.  This workflow passes:

```yaml
name: pydpkg

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: python3.11 -m pip install pydpkg
      - run: python3.11 -c 'import pydpkg'
```

Passing test run: https://github.com/memory/python-dpkg/actions/runs/3933979103/jobs/6728251105

The issue here is that, somewhat ironically, given the context of this entire project, managing python installations with apt/dpkg is a pretty fraught process:

Ubuntu 22.04 is built with python 3.10.4 as its default system python distribution, and ubuntu also packages a somewhat haphazard subset of popular pypi packages (notably, in this case, [cffi](https://pypi.org/project/cffi/)) in apt, e.g. `python3-cffi` and `python3-cffi-backend`.  22.04 _also_ offers python 3.11 as installable from apt, but there is no separate set of python module packages built against py3.11 that get installed alongside it (even optionally), so when you call code such as `python3.11 -m pip` it's actually running pip from the py3.10 modules dir at `/usr/lib/python3/dist-packages/pip` even though it's the 3.11 runtime calling the code.

Sometimes this is safe to do -- pip, obviously, functions fine in this context.  But sometimes it's not at all safe since there might be breaking changes between python versions and CFFI is more or less exactly the sort of package that you'd expect to be a problem.  This is an ongoing and basically unsolvable issue with using competing package management strategies with python; you can read a very very long diatribe about it here if you want to know more: https://github.com/pypa/pip/issues/5599

...all of which is why it's _really_ important, when testing python code in github actions, to use the [Setup Python Action](https://github.com/marketplace/actions/setup-python) rather than trying to DIY it with `apt install`.  The setup action does basically everything you'd want here: it creates and manages a standalone python install tree that does not intersect at all with the system one.

If your use case _outside_ of github actions involves running pydpkg under python 3.11 on an ubuntu:22.04 system, I strongly recommend using [pyenv](https://github.com/pyenv/pyenv) or a similar tool to build a self-contained python distribution.  You can probably get it to successfully import using the `python3.11` apt package by purging the `python3-cffi, python3-cffi-backend` packages before installing pydpkg, but not only do I not guarantee that that will not screw up some other piece of python tooling on your system but in fact I pretty much guarantee that it _will_:

```yaml
name: pydpkg
on:
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -qq python3.11
      - run: sudo apt-get purge -y python3-cffi python3-cffi-backend
      - run: python3.11 -m pip install pydpkg
      - run: python3.11 -c 'import pydpkg'
```

Passing test run [here](https://github.com/memory/python-dpkg/actions/runs/3933893246) but let me double down: this is a bad idea and you should not do it. :)
